apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy15
  labels:
    app: autodeploy15
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1717450474397
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy15
  template:
    metadata:
      labels:
        app: autodeploy15
    spec:
      containers:
        - name: autodeploy15
          image: acrworkflow1717450474397.azurecr.io/image-workflow-1717450474397:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
