apiVersion: v1
kind: Service
metadata:
  name: autodeploy15
  namespace: namespace-workflow-1717450474397
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy15
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000